# Generated by Django 3.2.9 on 2021-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('toiletId', models.IntegerField()),
                ('rating', models.FloatField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('topic', models.TextField()),
                ('text', models.TextField()),
                ('email', models.TextField()),
                ('date', models.DateField()),
                ('isChecked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Toilets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_id', models.IntegerField()),
                ('address', models.TextField()),
                ('serving', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField()),
                ('isConfirmed', models.BooleanField()),
            ],
        ),
    ]
