package com.example.wclookup.core.constant

object NameConstant {
    const val ID = "id"
    const val USER_ID = "userId"
    const val TOILET_ID = "toiletId"
    const val RATING = "rating"
    const val TEXT = "text"
    const val ADDRESS = "address"
    const val SCHEDULE = "schedule"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val NICKNAME = "nickname"
    const val APP_PREFERENCES = "appPreferences"
    const val ACCESS_TOKEN = "accessToken"
    const val REFRESH_TOKEN = "refreshToken"
    const val CONFIRMED = "confirmed"
    const val CREATION_TIME = "creationTime"
    const val SUBJECT = "subject"
    const val EMAIL = "email"
    const val RESOLVED = "resolved"
    const val DATA = "data"
    const val PAGE_NUMBER = "pageNumber"
    const val PAGE_SIZE = "pageSize"
    const val TOTAL_PAGES = "totalPages"
    const val TOTAL_ENTITIES = "totalEntities"
    const val ERROR_MESSAGE = "errorMessage"
}